import type { Metadata } from 'next';
import Link from 'next/link';
import { Cookie, Database, FileText, LockKeyhole, Mail, Server, ShieldCheck, UserRoundCheck } from 'lucide-react';
import PageHero from '../components/PageHero';
import { getLocale } from '../i18n.server';

export async function generateMetadata(): Promise<Metadata> { const locale = await getLocale(); return locale === 'es' ? { title: 'Política de privacidad', description: 'Información sobre los datos que trata YoControlo, para qué se utilizan y cómo ejercer tus derechos.' } : { title: 'Privacy policy', description: 'Information about the data YoControlo processes, why it is used and how to exercise your rights.' }; }

const sections = [
  ['responsable', 'Responsable'], ['datos', 'Datos tratados'], ['finalidades', 'Finalidades y bases'], ['proveedores', 'Proveedores'], ['conservacion', 'Conservación'], ['derechos', 'Tus derechos'], ['cookies', 'Cookies'], ['seguridad', 'Seguridad'],
];

export default async function PrivacyPage() {
  if (await getLocale() === 'en') return <EnglishPrivacyPage />;
  return <div className="yc-page">
    <PageHero eyebrow="Privacidad sin promesas vacías" icon={ShieldCheck} title="Qué sabemos, para qué lo usamos y qué puedes decidir." description="YoControlo necesita almacenar información para sincronizar tu cuenta y prestar el servicio. Esta política explica esa realidad con claridad." />
    <div className="yc-policy-layout">
      <aside><strong>Contenido</strong>{sections.map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>
      <article className="yc-policy-content">
        <section id="responsable"><FileText/><h2>1. Responsable</h2><p>El responsable del tratamiento es <strong>Néstor Calderón Pérez</strong>, desarrollador de YoControlo, con sede en España. Puedes plantear cualquier consulta de privacidad en <a href="mailto:soporte@yocontrolo.net?subject=Privacidad">soporte@yocontrolo.net</a>.</p><p>Última actualización: 16 de agosto de 2026.</p></section>
        <section id="datos"><Database/><h2>2. Qué datos tratamos</h2><h3>Cuenta e identidad</h3><p>Identificador de usuario, correo, nombre visible, imagen de perfil, proveedor de acceso, estado de la cuenta, roles, permisos, beneficios y metadatos necesarios para autenticación y administración.</p><h3>Información introducida en YoControlo</h3><p>Movimientos, categorías, gastos fijos, deudas, preferencias y demás información financiera que decides registrar. Para las funciones compartidas también tratamos grupos, membresías, amistades, invitaciones, repartos, confirmaciones y notificaciones.</p><h3>Seguridad y funcionamiento</h3><p>Datos técnicos y de actividad necesarios para iniciar sesión, prevenir abuso, aplicar límites, investigar errores y mantener trazabilidad administrativa. Si contactas con soporte, tratamos el contenido y los datos de contacto que incluyas.</p><div className="yc-policy-callout"><LockKeyhole/><p><strong>No pedimos credenciales bancarias.</strong> YoControlo no se conecta a tus bancos, no inicia transferencias y no custodia dinero.</p></div></section>
        <section id="finalidades"><UserRoundCheck/><h2>3. Para qué y con qué base</h2><ul><li><strong>Prestar el servicio:</strong> crear tu cuenta, sincronizar datos, ejecutar recurrencias y habilitar grupos. Base: ejecución de los términos aceptados.</li><li><strong>Proteger la plataforma:</strong> autenticar, controlar permisos, prevenir fraude y abuso, y conservar auditoría proporcionada. Base: interés legítimo y seguridad del servicio.</li><li><strong>Atender soporte:</strong> responder consultas y resolver incidencias. Base: ejecución del servicio o medidas solicitadas por ti.</li><li><strong>Analítica opcional:</strong> medir el uso de la web pública únicamente cuando la aceptas. Base: consentimiento, revocable en cualquier momento.</li><li><strong>Obligaciones legales:</strong> atender requerimientos válidos y conservar información cuando una norma lo exija.</li></ul></section>
        <section id="proveedores"><Server/><h2>4. Proveedores y destinatarios</h2><p>Usamos proveedores técnicos imprescindibles para operar el servicio, entre ellos Firebase Authentication/Google para identidad, Cloudflare para red y protección, y la infraestructura donde se ejecutan la API, la base de datos y las copias de seguridad. Solo reciben la información necesaria para su función y están sujetos a sus condiciones y garantías de protección de datos.</p><p>No vendemos tu información personal ni entregamos tu historial financiero a anunciantes. Si una transferencia internacional resulta necesaria por la infraestructura de un proveedor, se aplicarán los mecanismos previstos por la normativa de protección de datos.</p></section>
        <section id="conservacion"><Database/><h2>5. Cuánto tiempo conservamos los datos</h2><p>Los datos de la cuenta y la información que introduces se mantienen mientras la cuenta permanezca activa o hasta que solicites su eliminación. Algunos registros de seguridad, auditoría, copias temporales o datos sujetos a obligación legal pueden conservarse durante el periodo estrictamente necesario para proteger el servicio, atender responsabilidades o completar la eliminación técnica.</p><p>Las consultas de soporte se conservan mientras sean necesarias para resolverlas y documentar la atención prestada.</p></section>
        <section id="derechos"><ShieldCheck/><h2>6. Tus derechos</h2><p>Puedes solicitar acceso, rectificación, supresión, limitación, oposición o portabilidad cuando corresponda. También puedes retirar un consentimiento sin afectar al tratamiento anterior y presentar una reclamación ante la Agencia Española de Protección de Datos.</p><p>Para ejercerlos escribe a <a href="mailto:soporte@yocontrolo.net?subject=Ejercicio%20de%20derechos">soporte@yocontrolo.net</a>. Podremos pedir información razonable para verificar que eres la persona titular de la cuenta.</p></section>
        <section id="cookies"><Cookie/><h2>7. Cookies y almacenamiento del navegador</h2><p>La web utiliza almacenamiento esencial para recordar el tema, la sesión y tu elección de cookies. Google Analytics solo se carga si autorizas la categoría de analítica. Puedes cambiar la decisión desde el botón de cookies situado en la esquina inferior de la web.</p><p>Rechazar la analítica no impide navegar ni crear una cuenta.</p></section>
        <section id="seguridad"><LockKeyhole/><h2>8. Seguridad y cambios</h2><p>Aplicamos autenticación, autorización en servidor, separación de permisos, límites de uso, auditoría y medidas operativas destinadas a reducir accesos no autorizados. Ningún sistema conectado puede garantizar riesgo cero; por eso revisamos y mejoramos estas capas de forma continua.</p><p>Si esta política cambia de forma relevante, lo comunicaremos por la web, la aplicación o el correo asociado a la cuenta, según corresponda.</p></section>
        <div className="yc-policy-footer"><Mail/><div><strong>¿Tienes una pregunta de privacidad?</strong><p>Escríbenos y te responderemos con el contexto necesario.</p></div><Link className="yc-button yc-button-primary" href="mailto:soporte@yocontrolo.net?subject=Privacidad">Contactar</Link></div>
      </article>
    </div>
  </div>;
}

const englishSections = [['responsable','Controller'],['datos','Data processed'],['finalidades','Purposes and legal bases'],['proveedores','Providers'],['conservacion','Retention'],['derechos','Your rights'],['cookies','Cookies'],['seguridad','Security']];

function EnglishPrivacyPage() {
  return <div className="yc-page">
    <PageHero eyebrow="Privacy without empty promises" icon={ShieldCheck} title="What we know, why we use it and what you can decide." description="YoControlo needs to store information to synchronise your account and provide the service. This policy explains that reality clearly." />
    <div className="yc-policy-layout">
      <aside><strong>Contents</strong>{englishSections.map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>
      <article className="yc-policy-content">
        <section id="responsable"><FileText/><h2>1. Controller</h2><p>The data controller is <strong>Néstor Calderón Pérez</strong>, the developer of YoControlo, based in Spain. Send privacy questions to <a href="mailto:soporte@yocontrolo.net?subject=Privacy">soporte@yocontrolo.net</a>.</p><p>Last updated: 16 August 2026.</p></section>
        <section id="datos"><Database/><h2>2. Data we process</h2><h3>Account and identity</h3><p>User identifier, email address, display name, profile image, sign-in provider, account status, roles, permissions, benefits and metadata required for authentication and administration.</p><h3>Information entered in YoControlo</h3><p>Movements, categories, recurring expenses, debts, preferences and other financial information you choose to record. Shared features also process groups, memberships, friendships, invitations, splits, confirmations and notifications.</p><h3>Security and operation</h3><p>Technical and activity data needed to sign in, prevent abuse, apply limits, investigate errors and maintain administrative traceability. If you contact support, we process the message and contact details you include.</p><div className="yc-policy-callout"><LockKeyhole/><p><strong>We do not ask for bank credentials.</strong> YoControlo does not connect to your banks, initiate transfers or hold money.</p></div></section>
        <section id="finalidades"><UserRoundCheck/><h2>3. Purposes and legal bases</h2><ul><li><strong>Provide the service:</strong> create your account, synchronise data, process schedules and enable groups. Basis: performance of the accepted terms.</li><li><strong>Protect the platform:</strong> authenticate, enforce permissions, prevent fraud and abuse, and maintain proportionate audits. Basis: legitimate interest and service security.</li><li><strong>Provide support:</strong> answer questions and resolve incidents. Basis: performance of the service or steps requested by you.</li><li><strong>Optional analytics:</strong> measure use of the public website only when you accept it. Basis: consent, which can be withdrawn at any time.</li><li><strong>Legal obligations:</strong> respond to valid requests and retain information when required by law.</li></ul></section>
        <section id="proveedores"><Server/><h2>4. Providers and recipients</h2><p>We use technical providers required to operate the service, including Firebase Authentication/Google for identity, Cloudflare for network protection, and the infrastructure running the API, database and backups. They receive only the information needed for their role and are subject to their own data-protection commitments.</p><p>We do not sell personal information or disclose financial history to advertisers. Where a provider requires an international transfer, the safeguards required by data-protection law apply.</p></section>
        <section id="conservacion"><Database/><h2>5. Data retention</h2><p>Account data and information you enter are kept while the account remains active or until you request deletion. Security logs, audits, temporary backups or legally required records may remain for the time strictly necessary to protect the service, address liabilities or complete technical deletion.</p><p>Support enquiries are retained only as long as needed to resolve and document the assistance provided.</p></section>
        <section id="derechos"><ShieldCheck/><h2>6. Your rights</h2><p>Where applicable, you can request access, rectification, erasure, restriction, objection or portability. You may also withdraw consent without affecting earlier processing and complain to the Spanish Data Protection Agency.</p><p>Write to <a href="mailto:soporte@yocontrolo.net?subject=Data%20rights">soporte@yocontrolo.net</a>. We may request reasonable information to verify that you own the account.</p></section>
        <section id="cookies"><Cookie/><h2>7. Cookies and browser storage</h2><p>The website uses essential storage to remember the theme, session and cookie choice. Google Analytics loads only when you allow analytics. You can change this choice from the cookie button at the bottom of the website.</p><p>Rejecting analytics does not prevent browsing or account creation.</p></section>
        <section id="seguridad"><LockKeyhole/><h2>8. Security and changes</h2><p>We use authentication, server-side authorisation, separated permissions, usage limits, audits and operational measures intended to reduce unauthorised access. No connected system can promise zero risk, so these layers are reviewed and improved continuously.</p><p>If this policy changes materially, we will communicate it through the website, app or account email as appropriate.</p></section>
        <div className="yc-policy-footer"><Mail/><div><strong>Do you have a privacy question?</strong><p>Write to us and we will respond with the necessary context.</p></div><Link className="yc-button yc-button-primary" href="mailto:soporte@yocontrolo.net?subject=Privacy">Contact us</Link></div>
      </article>
    </div>
  </div>;
}
