import { pageMetadata } from '@/app/seo';
import type { Metadata } from 'next';
import Link from '@/app/components/LocalizedLink';
import { Ban, CircleDollarSign, FileCheck, Mail, Scale, ShieldCheck, UserRoundCheck, Users } from 'lucide-react';
import PageHero from '@/app/components/PageHero';
import { getLocale } from '@/app/i18n.server';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const locale = await getLocale(params);
  return pageMetadata('/terms', locale, locale === 'es' ? 'Términos de uso' : 'Terms of use', locale === 'es' ? 'Condiciones aplicables al acceso y uso de YoControlo.' : 'Terms that apply to access and use of YoControlo.');
}

const sections = [['servicio','El servicio'],['cuenta','Tu cuenta'],['contenido','Tus datos'],['grupos','Funciones compartidas'],['uso','Uso permitido'],['planes','Planes'],['disponibilidad','Disponibilidad'],['baja','Baja y suspensión'],['responsabilidad','Responsabilidad'],['cambios','Cambios y contacto']];

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) {
  if (await getLocale(params) === 'en') return <EnglishTermsPage />;
  return <div className="yc-page">
    <PageHero eyebrow="Condiciones claras" icon={Scale} title="Reglas comprensibles para usar YoControlo." description="Estos términos definen qué ofrece el servicio, qué esperamos de cada cuenta y qué límites conviene conocer antes de utilizarlo." />
    <div className="yc-policy-layout">
      <aside><strong>Contenido</strong>{sections.map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>
      <article className="yc-policy-content">
        <section id="servicio"><FileCheck/><h2>1. El servicio</h2><p>YoControlo es una aplicación de organización financiera personal. Permite registrar y consultar movimientos, gastos recurrentes, deudas, cuentas representadas y gastos compartidos. Al crear una cuenta o utilizar el servicio aceptas estos términos.</p><div className="yc-policy-callout"><CircleDollarSign/><p><strong>YoControlo no es un banco ni una entidad de pago.</strong> No custodia dinero, no ejecuta transferencias, no se conecta a tus cuentas bancarias y no ofrece asesoramiento financiero, fiscal o de inversión.</p></div></section>
        <section id="cuenta"><UserRoundCheck/><h2>2. Tu cuenta</h2><p>Debes proporcionar información válida, proteger tus credenciales y mantener actualizado el correo de acceso. Eres responsable de la actividad realizada desde tu cuenta, salvo que nos comuniques sin demora un acceso no autorizado.</p><p>Podemos exigir controles adicionales de seguridad, cerrar sesiones o limitar temporalmente acciones cuando sea necesario para proteger la cuenta o el servicio.</p></section>
        <section id="contenido"><ShieldCheck/><h2>3. La información que introduces</h2><p>Conservas la responsabilidad sobre los datos financieros y textos que introduces. Nos autorizas a tratarlos únicamente para prestar, sincronizar, proteger y mejorar técnicamente el servicio conforme a la <Link href="/privacy">Política de privacidad</Link>.</p><p>Debes comprobar la exactitud de saldos, recurrencias, repartos y cálculos antes de tomar decisiones. YoControlo es una herramienta de registro y puede contener errores, retrasos o información incompleta.</p></section>
        <section id="grupos"><Users/><h2>4. Grupos, invitaciones y pagos externos</h2><p>Las funciones compartidas muestran información a las personas que forman parte del grupo. Solo debes incluir contenido que estés autorizado a compartir.</p><p>Un “pago externo” refleja que una persona declara haber pagado por Bizum, efectivo, transferencia u otro medio ajeno a YoControlo. El receptor debe confirmarlo; la aplicación no verifica ni ejecuta el movimiento real.</p><p>Las invitaciones reiteradas a usuarios inexistentes, el acoso, el spam o la manipulación de confirmaciones pueden activar avisos, límites o suspensión de la cuenta.</p></section>
        <section id="uso"><Ban/><h2>5. Uso permitido y prohibido</h2><p>Puedes utilizar YoControlo para organizar tus propias finanzas y colaborar de buena fe en grupos. No puedes intentar acceder a cuentas ajenas, eludir controles, automatizar tráfico abusivo, introducir código malicioso, acosar a otras personas, explotar vulnerabilidades ni usar el servicio para una actividad ilegal.</p><p>Si descubres un posible problema de seguridad, comunícalo de forma responsable a <a href="mailto:soporte@yocontrolo.net?subject=Seguridad">soporte@yocontrolo.net</a> y evita acceder o divulgar datos de terceros.</p></section>
        <section id="planes"><CircleDollarSign/><h2>6. Planes y publicidad</h2><p>Las funciones disponibles pueden depender del plan asociado a la cuenta. En este momento la cuenta gratuita puede utilizarse sin introducir un método de pago. Los planes “Sin anuncios” y “Pro” se muestran como previsiones y no están a la venta hasta que la aplicación indique expresamente lo contrario.</p><p>Antes de activar una compra se informará del precio total, impuestos, duración, condiciones y derecho de desistimiento cuando resulte aplicable.</p></section>
        <section id="disponibilidad"><FileCheck/><h2>7. Disponibilidad y evolución</h2><p>Trabajamos para mantener el servicio disponible, pero no garantizamos funcionamiento continuo ni ausencia absoluta de errores. Puede haber mantenimiento, cambios de infraestructura o incidencias de proveedores externos.</p><p>Podemos modificar, añadir o retirar funciones para mejorar seguridad, rendimiento o utilidad. Cuando un cambio afecte de forma relevante al uso o a tus derechos, intentaremos comunicarlo con antelación razonable.</p></section>
        <section id="baja"><UserRoundCheck/><h2>8. Baja, bloqueo y suspensión</h2><p>Puedes solicitar la eliminación de tu cuenta desde la aplicación o mediante soporte. Podemos limitar o suspender cuentas que incumplan estos términos, pongan en riesgo la seguridad, abusen de invitaciones o perjudiquen a otras personas.</p><p>Cuando sea razonablemente posible, explicaremos el motivo y ofreceremos un canal de revisión. La información se eliminará según la Política de privacidad y las obligaciones técnicas o legales aplicables.</p></section>
        <section id="responsabilidad"><Scale/><h2>9. Responsabilidad</h2><p>YoControlo no responde de decisiones financieras tomadas basándose exclusivamente en la aplicación, de operaciones realizadas fuera del servicio, de errores introducidos por usuarios ni de pérdidas indirectas que no puedan atribuirse legalmente al responsable.</p><p>Nada de estos términos limita derechos irrenunciables de consumidores ni responsabilidades que la ley no permita excluir.</p></section>
        <section id="cambios"><Mail/><h2>10. Cambios, ley aplicable y contacto</h2><p>Última actualización: 16 de agosto de 2026. Los términos se rigen por la legislación española, sin perjuicio de las normas imperativas y del fuero que corresponda a consumidores.</p><p>El responsable del servicio es <strong>Néstor Calderón Pérez</strong>. Para consultas sobre estos términos escribe a <a href="mailto:soporte@yocontrolo.net?subject=Términos%20de%20uso">soporte@yocontrolo.net</a>.</p></section>
        <div className="yc-policy-footer"><Mail/><div><strong>¿Algo no está claro?</strong><p>Preferimos resolver una duda antes de que aceptes algo que no entiendes.</p></div><Link className="yc-button yc-button-primary" href="mailto:soporte@yocontrolo.net?subject=Términos%20de%20uso">Contactar</Link></div>
      </article>
    </div>
  </div>;
}

const englishSections = [['servicio','The service'],['cuenta','Your account'],['contenido','Your data'],['grupos','Shared features'],['uso','Permitted use'],['planes','Plans'],['disponibilidad','Availability'],['baja','Deletion and suspension'],['responsabilidad','Liability'],['cambios','Changes and contact']];

function EnglishTermsPage() {
  return <div className="yc-page">
    <PageHero eyebrow="Clear conditions" icon={Scale} title="Understandable rules for using YoControlo." description="These terms define what the service provides, what we expect from each account and which limits you should understand before using it." />
    <div className="yc-policy-layout">
      <aside><strong>Contents</strong>{englishSections.map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</aside>
      <article className="yc-policy-content">
        <section id="servicio"><FileCheck/><h2>1. The service</h2><p>YoControlo is a personal finance organisation app. It lets you record and view movements, recurring expenses, debts, represented accounts and shared expenses. By creating an account or using the service, you accept these terms.</p><div className="yc-policy-callout"><CircleDollarSign/><p><strong>YoControlo is not a bank or payment institution.</strong> It does not hold money, execute transfers, connect to bank accounts or provide financial, tax or investment advice.</p></div></section>
        <section id="cuenta"><UserRoundCheck/><h2>2. Your account</h2><p>You must provide valid information, protect your credentials and keep your sign-in email up to date. You are responsible for activity performed through your account unless you promptly report unauthorised access.</p><p>We may require additional security checks, close sessions or temporarily limit actions when necessary to protect the account or service.</p></section>
        <section id="contenido"><ShieldCheck/><h2>3. Information you enter</h2><p>You remain responsible for the financial data and text you enter. You allow us to process it only to provide, synchronise, protect and technically improve the service under the <Link href="/privacy">Privacy policy</Link>.</p><p>Check balances, schedules, splits and calculations before making decisions. YoControlo is a recording tool and may contain errors, delays or incomplete information.</p></section>
        <section id="grupos"><Users/><h2>4. Groups, invitations and external payments</h2><p>Shared features display information to people in the group. Only include content you are authorised to share.</p><p>An “external payment” records that someone says they paid by transfer, cash or another method outside YoControlo. The recipient must confirm it; the app neither verifies nor executes the real payment.</p><p>Repeated invitations to nonexistent users, harassment, spam or manipulated confirmations may trigger warnings, limits or account suspension.</p></section>
        <section id="uso"><Ban/><h2>5. Permitted and prohibited use</h2><p>You may use YoControlo to organise your own finances and collaborate in good faith. You may not access other accounts, bypass controls, automate abusive traffic, introduce malicious code, harass people, exploit vulnerabilities or use the service illegally.</p><p>Report potential security issues responsibly to <a href="mailto:soporte@yocontrolo.net?subject=Security">soporte@yocontrolo.net</a> and avoid accessing or disclosing third-party data.</p></section>
        <section id="planes"><CircleDollarSign/><h2>6. Plans and advertising</h2><p>Available features may depend on the account plan. The free account can currently be used without a payment method. “Ad-free” and “Pro” plans are previews and are not for sale until the app expressly says otherwise.</p><p>Before a purchase is enabled, we will state the total price, taxes, duration, conditions and any applicable right of withdrawal.</p></section>
        <section id="disponibilidad"><FileCheck/><h2>7. Availability and evolution</h2><p>We work to keep the service available but cannot guarantee uninterrupted or error-free operation. Maintenance, infrastructure changes or provider incidents may occur.</p><p>Features may be changed, added or removed to improve security, performance or usefulness. When a change materially affects use or your rights, we will try to provide reasonable notice.</p></section>
        <section id="baja"><UserRoundCheck/><h2>8. Deletion, blocking and suspension</h2><p>You may request account deletion from the app or through support. We may restrict or suspend accounts that breach these terms, put security at risk, abuse invitations or harm others.</p><p>Where reasonably possible, we will explain the reason and provide a review channel. Information is deleted under the Privacy policy and applicable technical or legal obligations.</p></section>
        <section id="responsabilidad"><Scale/><h2>9. Liability</h2><p>YoControlo is not responsible for financial decisions based solely on the app, operations outside the service, errors entered by users or indirect losses that cannot legally be attributed to the controller.</p><p>Nothing in these terms limits mandatory consumer rights or liability that cannot lawfully be excluded.</p></section>
        <section id="cambios"><Mail/><h2>10. Changes, governing law and contact</h2><p>Last updated: 16 August 2026. These terms are governed by Spanish law, without limiting mandatory consumer rules or the jurisdiction legally available to consumers.</p><p>The service controller is <strong>Néstor Calderón Pérez</strong>. Send questions to <a href="mailto:soporte@yocontrolo.net?subject=Terms%20of%20use">soporte@yocontrolo.net</a>.</p></section>
        <div className="yc-policy-footer"><Mail/><div><strong>Is something unclear?</strong><p>We would rather answer a question before you accept something you do not understand.</p></div><Link className="yc-button yc-button-primary" href="mailto:soporte@yocontrolo.net?subject=Terms%20of%20use">Contact us</Link></div>
      </article>
    </div>
  </div>;
}
